### PR TITLE
Make saving and restoring float registers optional

### PR DESCRIPTION
**Pull request by MabezDev**
Closes https://github.com/esp-rs/xtensa-lx/issues/27

I once again tried it out on esp-wifi, but sadly it didn't seem to make much difference. I guess there is a bottleneck somewhere else for Xtensa.

### CODE REVIEW

**Comment by bjoernQ** [comment]
Code is fine and in general I agree with #27 but it's probably footgun material - whenever someone runs into it, it would be fun to debug that 🤔 

What esp-idf does for context switching (and what we shouldn't do IMHO) is to disable the FPU and as soon as it gets used their exception handler will save the float regs and enable it - when returning they remember if they need to restore the float regs

Maybe we should at least disable the FPU while the interrupt handler runs? Still a bit more overhead than doing nothing but hopefully cheaper than saving / restoring all those (mostly unused) registers

t.b.h. I'm not sure if this will ever be an issue - just wanted to mention it before LGTMing it

My guess would be that spilling the registers is quite expensive - we could and probably should have some "fast path" interrupts in future (we could save some of the save / restore cost also for RISCV) but unfortunately for esp-wifi's task switching we definitely need all that. I also thought about making interrupts generally cheap and come up with a "new" idea for task switching .... I just don't have that new idea, yet

**Comment by MabezDev** [comment]
> Maybe we should at least disable the FPU while the interrupt handler runs? Still a bit more overhead than doing nothing but hopefully cheaper than saving / restoring all those (mostly unused) registers

The idea here is that if they someone uses floats here without the FPU enabled they'll get a fault instead of silently doing bad things? Sounds good to me, thanks for that! I will look into that soon.

**Comment by MabezDev** [comment]
image

Thanks for the pointer, this is much better! Nice idea :).

**Review by bjoernQ — APPROVED** [review]
LGTM - good idea

**Comment by bjoernQ** [comment]
FYI I checked how expensive spilling the registers is and it's around 53 cycles - it's not nothing but much less than what I expected

**Pull request merged**
